# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rmm9yQ-eiZMzSsSstE1WAm8utN6SwwTe
"""

import pandas as pd
import matplotlib.pyplot as plt

# STEP 1: LOAD DATA (FIX HERE)
df = pd.read_csv("/content/Untitled spreadsheet - train.csv", encoding='latin1')

print(df.head())

# STEP 2: CLEAN COLUMNS
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("\nCleaned Columns:")
print(df.columns)

# STEP 3: DATE CONVERSION (FIXED)
if 'order_date' in df.columns:
    df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
else:
    print("Column 'order_date' not found")

# STEP 4: REMOVE MISSING VALUES
df = df.dropna()

# STEP 5: TOP PRODUCTS
top_products = df.groupby('product_name')['sales'].sum()
top_products = top_products.sort_values(ascending=False).head(10)

print("\nTop 10 Products:")
print(top_products)

# STEP 6: REGION PERFORMANCE
region_sales = df.groupby('region')['sales'].sum()
print("\nRegion Performance:")
print(region_sales)

# STEP 7: CATEGORY PERFORMANCE
category_sales = df.groupby('category')['sales'].sum()
print("\nCategory Performance:")
print(category_sales)

# STEP 8: VISUALIZATION

# Bar Chart
top_products.plot(kind='barh')
plt.title("Top Selling Products")
plt.xlabel("Sales")
plt.ylabel("Products")
plt.show()

# Pie Chart
category_sales.plot(kind='pie', autopct='%1.1f%%')
plt.title("Category Distribution")
plt.ylabel("")
plt.show()

# Monthly Trend
df['month'] = df['order_date'].dt.to_period('M')
monthly_sales = df.groupby('month')['sales'].sum()

monthly_sales.plot(kind='line')
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()